#!/bin/bash
set -xue
echo "===============START================" >> bashScript.log
new_user=$1
if [ -n "$new_user" ]
then
  if sudo adduser "$new_user" --disabled-password --gecos ""; then
    echo "NEW USER ---> " "$new_user" >> bashScript.log
  else
    echo "| Fail: user " "$new_user" " has already been created |" >> bashScript.log
    echo "===============STOP==============" >> bashScript.log
  fi
  sudo usermod -aG sudo "$new_user"
  sudo mkdir /home/"$new_user"/.ssh
  sudo chown -R "$new_user":"$new_user" /home/"$new_user"/.ssh/
  sudo chmod 777 /home/"$new_user"/.ssh
  sudo touch /home/"$new_user"/.ssh/authorized_keys
  sudo chown -R "$new_user":"$new_user" /home/"$new_user"/.ssh/authorized_keys
  sudo chmod 777 /home/"$new_user"/.ssh
  sudo chmod 777 /home/"$new_user"/.ssh/authorized_keys
  sudo cat /home/ilya/id_rsa.pub > /home/"$new_user"/.ssh/authorized_keys
  sudo rm id_rsa.pub
  sudo chmod 600 /home/"$new_user"/.ssh/authorized_keys
  sudo chmod 700 /home/"$new_user"/.ssh
else
  echo "!!No parameters user for script!! "
fi
echo "===============SUCCESS==============="  >> bashScript.log
